fix(bashrc): export path before exit-if-not-bash
- move path export and reboot notice before non-bash exit
- disable nvm initialization
- minor linter fixes

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -23,23 +23,6 @@ if [ -z "$BASH_PROFILE_LOADED" ] && [ -f "$HOME/.bash_profile" ]; then
   . "$HOME/.bash_profile"
 fi
 
-###### EXITS
-## IF NOT INTERACTIVE
-case $- in
-*i*) ;;
-*) return ;;
-esac
-## EXIT IF NOT BASH
-if [ -z "$BASH_VERSION" ]; then
-  export PATH
-  # shellcheck disable=SC2317
-  return &>/dev/null || exit
-fi
-## REBOOT CHECKS
-if [[ "$(uname -s)" == "Linux" ]] && [[ -f /var/run/reboot-required ]]; then
-  echo "*** System restart required ****"
-fi
-
 ###### PATHS
 pathIf "/opt/homebrew/bin"
 pathIf "/opt/homebrew/sbin"
@@ -49,6 +32,26 @@ pathIf "$HOME/bin"
 pathIf "$HOME/go/bin"
 pathIf "/usr/local/go/bin"
 pathIfPre "$HOME/.local/bin"
+
+## REBOOT CHECKS
+if [[ "$(uname -s)" == "Linux" ]] && [[ -f /var/run/reboot-required ]]; then
+  echo "*** System restart required ****"
+fi
+
+
+###### EXITS
+## IF NOT INTERACTIVE
+case $- in
+  *i*) ;;
+  *) return ;;
+esac
+## EXIT IF NOT BASH
+if [ -z "$BASH_VERSION" ]; then
+  export PATH
+  # shellcheck disable=SC2317
+  return &>/dev/null || exit
+fi
+
 
 ###### BASH CONFIGURATION
 # don't put duplicate lines or lines starting with space in the history.
@@ -82,9 +85,9 @@ umask 0002
 major_version=${BASH_VERSION%%.*}
 if command -v oh-my-posh &>/dev/null && [ "$TERM_PROGRAM" != "Apple_Terminal" ] && [ "$major_version" -ge 5 ]; then
   ## OHMYPOSH - if OMP installed and modern Bash and terminal
-  eval "$(oh-my-posh init bash --config $DOTFILES/themes/tokyonights-bash.omp.toml)"
+  eval "$(oh-my-posh init bash --config "$DOTFILES/themes/tokyonights-bash.omp.toml")"
 else
-  . $DOTFILES/shell/bash-prompt
+  . "$DOTFILES/shell/bash-prompt"
 fi
 
 ###### OS-SPECIFIC CONFIGURATION
@@ -128,9 +131,9 @@ if [ "$TERM" != dumb ] && [ -n "$GRC" ]; then
 fi
 
 ### setup NVM
-export NVM_DIR="$HOME/.nvm"
-[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"                                       # This loads nvm
-[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
+# export NVM_DIR="$HOME/.nvm"
+# [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"                                       # This loads nvm
+# [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
 
 ###### COMPLETIONS
 ## jujutsu completion
@@ -146,11 +149,9 @@ if command -v fzf >/dev/null 2>&1; then
 fi
 
 ###### SOURCE FILES
-
 ## CROSS-SHELL FILES
-sourceIf "$DOTFILES/shell/includes" # includes file    - zsh & bash
-
+sourceIf "$DOTFILES/shell/includes"                 # includes file - bash
 ## EXTERNAL FILES
-sourceIf "$DOTFILES/private/shell/bashrc-private" # private bashrc   - bash
+sourceIf "$DOTFILES/private/shell/bashrc-private"   # private bashrc - bash
 
 # vim: ft=bash
